// Generated by CoffeeScript 1.4.0
var _site;

window.URL = window.URL || window.webkitURL;

navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;

_site = {};

_site.video = document.querySelector('video');

_site.getUserMediaCallback = function(stream) {
  return _site.video.src = window.URL.createObjectURL(stream);
};

_site.setVideoFilter = function(effectName, effectValue) {
  var $video, currentFilters, filter, filterValue, filters, regExp, _i, _len;
  $video = $(_site.video);
  filters = ['-webkit-filter', '-moz-filter', '-o-filter', '-ms-filter', 'filter'];
  currentFilters = null;
  for (_i = 0, _len = filters.length; _i < _len; _i++) {
    filter = filters[_i];
    if ($video.css(filter) !== 'none') {
      currentFilters = $video.css(filter);
      break;
    }
  }
  regExp = new RegExp("" + effectName + "\\([\-0-9a-zA-Z\.]+\\)");
  filterValue = currentFilters.replace(regExp, "" + effectName + "(" + effectValue + ")");
  if (typeof console !== "undefined" && console !== null) {
    console.log(filterValue);
  }
  return $video.css({
    '-webkit-filter': filterValue,
    '-moz-filter': filterValue,
    '-o-filter': filterValue,
    '-ms-filter': filterValue,
    'filter': filterValue
  });
};

_site.getUserMediaFallBack = function(e) {
  alert("Your browser dosen't support 'navigator.getUserMedia'");
  return typeof console !== "undefined" && console !== null ? console.log(e) : void 0;
};

if (!navigator.getUserMedia) {
  _site.getUserMediaFallBack();
} else {
  navigator.getUserMedia({
    audio: true,
    video: true
  }, _site.getUserMediaCallback, _site.getUserMediaFallBack);
}

$(function() {
  $("#range-for-brightness").change(function() {
    return _site.setVideoFilter("brightness", $(this).val());
  });
  $("#range-for-blur").change(function() {
    return _site.setVideoFilter("blur", "" + ($(this).val()) + "px");
  });
  $("#range-for-saturate").change(function() {
    return _site.setVideoFilter("saturate", "" + ($(this).val()));
  });
  $("#range-for-hue-rotate").change(function() {
    return _site.setVideoFilter("hue-rotate", "" + ($(this).val()) + "deg");
  });
  $("#range-for-contrast").change(function() {
    return _site.setVideoFilter("contrast", "" + ($(this).val()) + "%");
  });
  $("#range-for-invert").change(function() {
    return _site.setVideoFilter("invert", "" + ($(this).val()) + "%");
  });
  $("#range-for-grayscale").change(function() {
    return _site.setVideoFilter("grayscale", "" + ($(this).val()) + "%");
  });
  return $("#range-for-sepia").change(function() {
    return _site.setVideoFilter("sepia", "" + ($(this).val()) + "%");
  });
});
